create table [dbo].[UserTasks]
(
	[UserTaskId] INT NOT NULL IDENTITY,
	[TaskId] INT NOT NULL,
	[UserId] INT NOT NULL,
	[StateId] INT NOT NULL

	CONSTRAINT PK_UserTaskId PRIMARY KEY (UserTaskId),

	CONSTRAINT FK_UserTask_Task FOREIGN KEY (TaskId) REFERENCES Tasks(TaskId) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_UserTask_UserProfile FOREIGN KEY (UserId) REFERENCES UserProfiles(UserId) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_UserTask_TaskState FOREIGN KEY (StateId) REFERENCES TaskStates(StateId) ON DELETE CASCADE ON UPDATE CASCADE,
)